### ISSUE TITLE
Wiki: UDF filesystem check tools?

### ISSUE THREAD

**Issue by GreatEmerald** [JElchison/format-udf#14]
This may be a bit out of scope for this project, but I'm thinking that a place documenting the available UDF fsck tools would be nice. One of the main problems why UDF isn't used more on Linux is the lack of a filesystem check tool; the one provided by udf-tools is basically /bin/true.

There's apparently also udf_test from something called Philips UDF Conformance Tool; but I can't actually find it and I'm not sure if it actually fixes problems, or  just finds them. Looking at Google results, the last release of it might have been in 2007, which would mean it would cover all UDF revisions.

I see that Windows does have the ability to check UDF volumes; in fact, it seems that my Win10 installation claims to have repaired the volume I created with format-udf, even if I didn't actually put any files on it. I wonder what it changes... (Hopefully not the MBR?)

Apparently there's also a check tool for Solaris, which perhaps could be ported to Linux too: https://bugs.launchpad.net/ubuntu/+source/udftools/+bug/384156#3

Does OS X have a UDF check tool to begin with?

**Comment by JElchison** [comment]
Hi @GreatEmerald, thanks for the post!  Yes, I think think is a great topic for a wiki page.  I've started one with placeholders [here](https://github.com/JElchison/format-udf/wiki/fsck-tools-for-UDF).  Would you like the honors of kicking it off?  Even a copy/paste from what you posted above would be great.

Thanks!

**Comment by GreatEmerald** [comment]
Done. Added as much info as I could gather.

**Comment by JElchison** [comment]
Looks great.  Many thanks, @GreatEmerald!

**Comment by JElchison** [comment]
FYI, I've (barely) started a Linux port of the Solaris UDF fsck.  Help wanted!  :)

https://github.com/JElchison/udf-fsck

**Comment by unxed** [comment]
https://github.com/pali/udftools
