### ISSUE TITLE
Usable for a shared partition on a multi-boot system?

### ISSUE THREAD

**Issue by danryu** [JElchison/format-udf#19]
I was looking to use UDF to format a shared Linux/Win/OSX data partition on laptops.

Is this approach suitable for this use case?

**Comment by JElchison** [comment]
I've not tried myself, but seems plausible. Highly dependent on your choice of bootloader. GRUB 2 seems like it's both cross-platform and supports UDF. 

Report back with your findings? 

Thanks!

**Comment by JElchison** [comment]
hi @danryu, since it's been over 3 months, i'm assuming you didn't find anything interesting.  as such, i'm closing this issue for now.  however, feel free to re-comment if you discover anything.  thanks!

**Comment by danryu** [comment]
Hi @JElchison, sorry, I changed requirements in the end, deciding to go for a single-boot system and lots of virtualbox instead. But I still think that for a general-purpose shared data partition for any multi-boot systems, going UDF seems to have the least compromises as far as I can tell. NTFS works fine on a Linux/Windows boot until you want to apply permissions and the like and then things get complicated.
Still gonna try your script next time I'm formatting some flash drives though, thanks!
