### ISSUE TITLE
How to run script on windows?

### ISSUE THREAD

**Issue by mchiasson** [JElchison/format-udf#20]
Tried running this script in msys2 on Windows 10. Can't find diskutil or blockdev. Where can I find any of these two?

**Comment by JElchison** [comment]
Hi @mchiasson.  format-udf was targeted for POSIX shells, specifically Linux and OS X (please refer to the readme).  The reason why is the exact reason you're asking.  Windows simply doesn't provide native ways to accomplish tasks the same way that POSIX shells do.

Unfortunately, I won't be able to provide support for msys.  But you're always welcome to report back here if you're successful.

Good luck!

**Comment by mchiasson** [comment]
Thanks. I got my USB stick to work when formatted on linux. Works on all 3 platforms flawlessly. Thank you for this awesome script.

**Comment by JElchison** [comment]
Glad to hear it. Cheers!
