### ISSUE TITLE
USB stick formatted on OS X not recognized in Windows 10

### ISSUE THREAD

**Issue by mchiasson** [JElchison/format-udf#21]
I tried formatting the thing using format-udf in both linux and osx. Everything works fine between these two OSes, but when I connect the usb stick on Windows 10, it doesn't recognize it and wants to format it.

**Comment by JElchison** [comment]
Hello again, @mchiasson.  format-udf is just a wrapper for standard UDF-formatting tools.  As such, it's unlikely that format-udf can do anything better to enable support for Windows 10.

For more info, check out the compatibility table on the readme.  Also, https://en.wikipedia.org/wiki/Universal_Disk_Format#Compatibility

Please report back if you learn of something that format-udf can do better to improve support for Windows 10.

Thanks!

**Comment by mchiasson** [comment]
I discovered that when I run `format-udf`on linux, then the usb key works fine in Windows 10.  It looks like there might be a problem with either newfs_udf itself, or the fake mbr part when executed on osx

**Comment by JElchison** [comment]
Interesting. 

The fake MBR is written regardless of whether run on Linux or OS X. 

I'm reopening this issue as a reminder to learn whether there's a difference between mkudffs and newfs_udf in terns of Windows 10 recognition.

**Comment by mchiasson** [comment]
If this helps, I am currently running on OSX Yosemite (10.10)

**Comment by JElchison** [comment]
Recent revelations on other issues may indicate that another factor here may be block size on the drive in question.  See the clarifying text I've just [added](https://github.com/JElchison/format-udf/blob/master/README.md#block-size) on the README.  Essentially, there's not much that format-udf can do if OSes have trouble auto-mounting drives with certain block sizes.

Still leaving this issue open until we learn whether there's a difference between mkudffs and newfs_udf in terns of Windows 10 recognition.

**Comment by polarathene** [comment]
Not sure if this is a viable idea, but since macOS and Windows can both run a light VM to run Docker containers, perhaps that could be a viable alternative that the two OS could use, ensuring they all format based off the linux utils(which are apparently better?)

Not sure how well that works with this use case though, as permissions and access/visibility of the disk to format might complicate it a bit.

**Comment by walterav1984** [comment]
Not an issue for me anymore using format-udf 1.7.1 on MacOS Yosemite 10.10.5, formating a 4GB USB device which can be read/write fine under Windows 10 Home 64bit (1903).

**Comment by JElchison** [comment]
Closing this per @walterav1984's previous comment.

Note for posterity:  We never learned whether there's a difference between mkudffs and newfs_udf in terms of Windows 10 recognition.
