### ISSUE TITLE
Let <device> parameter have '/dev/' prefix

### ISSUE THREAD

**Issue by JElchison** [JElchison/format-udf#25]
[Suggested](https://github.com/JElchison/format-udf/issues/24#issuecomment-186549294) by @lucky62 in #24:

Please consider to allow `/dev/` prefix for the device name. So both formats will be possible:
- without `/dev/` - e.g. sdb or sdb2
- with `/dev/` - e.g. /dev/sdb or /dev/sdb2

I see that `/dev/$DEVICE` pattern is used many times in your script so I think better is to check at the beginning if has the `/dev/` prefix and add it if not. Then you can use simple `$DEVICE` instead of `/dev/$DEVICE`.

**Comment by yodor** [comment]
Hello maybe also enable sr0-9 type devices for optical media ?
