### ISSUE TITLE
allow virtual block devices

### ISSUE THREAD

**Issue by tristan-k** [JElchison/format-udf#27]
I'm trying to format a veracrypt encrypted device with `format-udf` but it fails because it only searches for devices in the `/dev/` directory. I changed every appearance of `/dev/$Device` to `/dev/mapper/$DEVICE` but the script complains about:

```
[-] <device> is of invalid form
```

Please allow [virtual block devices](https://en.wikipedia.org/wiki/Device_mapper) to be formatted with  `format-udf`.

**Comment by JElchison** [comment]
Hi @tristan-k!  Thanks for the note.  This is a good idea.

The easy workaround for you is to simply comment out line 354:

```
(echo "$DEVICE" | egrep -q '^(([hs]d[a-z])([1-9][0-9]*)?|(disk[0-9]+)(s[1-9][0-9]*)?)$') || (echo "[-] <device> is of invalid form" >&2; false)
```

This will allow the validation to pass that you were running into.  You may have to comment out a similar check a few lines below (line 379).

However, after having removing this validation, you may then run into the reason for which the validation exists, which is verifying that the requested partition type matches the device provided (i.e. partition or entire disk).  (Recall that UDF was designed for entire-disk formatting.)  I'm curious how udftools will perform on that type of mapped block device.

I don't have a `/dev/mapper/` device setup that would allow me to test at the moment.  Would you mind reporting back after you give it a shot?

If you're successful, I have some ideas on how to more elegantly add support for mapper devices.

**Comment by Heziode** [comment]
Hi,

I've test your suggestion @JElchison (plus some edit) and this work fine (on Linux and Windows).

Lines I've commented :
- 309
- 334
- 614
- 615
