### ISSUE TITLE
Add capability to (optionally) zero entire drive (may take a long time)

### ISSUE THREAD

**Issue by JElchison** [JElchison/format-udf#3]
This would take a new command-line option as well.

Consider a progress meter?  http://linuxcommando.blogspot.com/2008/06/show-progress-during-dd-copy.html

**Comment by IvanAnishchuk** [comment]
Good idea. It can be implemented using shred(1), for paranoid security specialists :)

**Comment by JElchison** [comment]
In interest of keeping the scope of format-udf narrow, I've decided against this enhancement.  Users can use any means they want to zero/scrub/shred a disk before calling format-udf.  No need to increase format-udf's dependencies, either.
