### ISSUE TITLE
Crucial M550 bricked

### ISSUE THREAD

**Issue by fawxes** [JElchison/format-udf#37]
Greetings,

thanks for the script. Made my life much easier, due to handling with different operating systems.

I have a raspberry pi running with raspbian jessie. I formated multiple USB pen drives with success but had a misfortune with my beloved external SSD in an USB enclosure driven by an AsMedia 1351 chipset.

When the script started the format process I could hear a buzz coming from the drive. Sometimes later the procedure stopped with an I/O timeout error. Plugging out and plugging it back unfortunately didn't bring back the drive. After attaching it to a Windows PC I tried to force a Firmware update via Crucial's Storage Executive to no avail. Sadly enough I can't read any SMART data with various tools depending on the mood of the drive. Sometimes it manages to give some data (with healthy data), sometimes its garbage. I even tried to issue an ATA Secure Erase which sometimes proceeds as it should but without any results.

Since the drive still gets recognized, I thought I might fiddle with hdparm aswell. So if anyone has a magic up their sleeves with hdparm I'm ready to be a guinea pig.

Last week I got hands on a Samsung 850 Pro. I followed exactly the same procedure in the same enclosure with the rpi with positive results. I do now have quite a fast external drive with UDF, although with some casualties on the way.

PS: both drives report(-ed) 512 for physical and logical block size

**Comment by JElchison** [comment]
Do the sounds persist on your M550?  Usually sounds are indicative of a hardware problem (and usually not recoverable).

What happens when trying to use `dd` to write zeroes to the entire drive?  https://wiki.archlinux.org/index.php/benchmarking#dd

[f3read](http://manpages.ubuntu.com/manpages/trusty/man1/f3read.1.html) may also be helpful.

> I followed exactly the same procedure in the same enclosure with the rpi with positive results.

Does "positive results" mean that format-udf succeeded?  Or that the procedure also bricked your 850 Pro?

I'm interested whether you have a procedure that reproducibly bricks drives.  Or if your problems are isolated to your M550.

If your problems are reproducible, I'm interested exactly what step inside format-udf starts the problem.  (Can you re-attempt using `set -x` at top of Bash script?)  This will be helpful if there is a problem with format-udf, or one of the utilities that it calls.

**Comment by fawxes** [comment]
The sound of the SSD was different. It always did emit distinctive sounds when it was reading/writing, but when it went broke, it was totally different. If I plug it now it's apparently idle, nothing audible, just like it was before. The SMART data was fine before the procedure aswell. Since it was my first external SSD I was interested in its durability, thus regular SMART checks were made.

I made a misunderstanding with dd. I meant hdparm for experiments. Currently dd is not useful since no partitions are adressable.

When I try to issue a Secure Erase or a dco restore with hdparm, both commands return the same error:
SG_IO bad/missing sense data, sb[]: gibberish...

The format went successful with the 850 Pro and is still up and running without any issues.

As of now I can't distinguish the source of the problem. Either it's the AsMedia 1351 USB/SATA Bridge which has other issues (ex. connecting both host and enclosure via USB Type-C cable and reading / writing on a drive that exceeds USB 3.0 / 3.1 Gen1 speeds causes an I/O error and freezes either host or the drive) OR there is an issue with Marvell controllers running with Crucial FW. I think the problem is isolated to the Marvell controller, since the Samsung drive survived the same procedure in the same enclosure with the AsMedia Chip.

Unfortunately I'm missing more drives for a more profound testing.

**Comment by JElchison** [comment]
dd can be used to write directly to the device, no partitions required. That's actually what format-udf does to blow away the old partition table. I'm curious whether you can use dd to write zeroes to the entire drive.

f3read will do the same.

Both of these above methods will trash existing contents on the drive, but will help ascertain where problems exist, if any.

If you decide to try it, please report back with results from dd and/or f3read

**Comment by fawxes** [comment]
Hello again,
firing up dd didn't yield any viable results. The drive was stuck in an infinite loop I assume. I let dd run for around 1,5 days and not even an error was reported back but the drive LED was still blinking all the time.

I've tried my luck f3probe, here are the results:
>F3 probe 6.0
>Bad news: The device `/dev/sda' is damaged
>
>Device geometry:
>	         *Usable* size: 0.00 Byte (0 blocks)
>	        Announced size: 238.47 GB (500118192 blocks)
>	                Module: 256.00 GB (2^38 Bytes)
>	Approximate cache size: 0.00 Byte (0 blocks), need-reset=no
>	   Physical block size: 512.00 Byte (2^9 Bytes)
>
>Probe time: 55'10"
> Operation: total time / count = avg time
>      Read: 0us / 0 = 0us
>     Write: 55'10" / 4096 = 808.2ms
>     Reset: 0us / 0 = 0us

I'm actually willing to send the drive to you, but it depends on the shipping costs it will cause. At this point I don't know if the drive can be even resurrected.

**Comment by JElchison** [comment]
Hi @fawxes. Sorry to hear this  :-/

I'm not a data retrieval expert, so I'm not sure what I'd do with the drive that you haven't already tried.  Any chance it's still under warranty from the manufacturer?  It seems like the manufacturer (or a data retrieval expert) might be able to help diagnose the drive further...

**Comment by fawxes** [comment]
Hello @JElchison 
No problem, luckily the drive was expendable, Backups were made. Unfortunately the drive's warranty has expired sometime ago. Anyway It was a nice lecture for how SSD Controllers react to commands differently when used in an Enclosure. Nevertheless thank you for helping out!

Cheers

**Comment by JElchison** [comment]
Happy to do it.  Thanks for reporting, and hopefully you have better luck in the future!
