### ISSUE TITLE
Script fails with udftools 2.0+

### ISSUE THREAD

**Issue by lafleurdeboum** [JElchison/format-udf#40]
The script as is failed in Ach linux, using udftools 2.0-2 ; the error was :

`mkudffs: Error: Option --media-type must be specified before option --udfrev`

So I just edited the script ; I moved the --media-type option before the --udfrev option and retried. It then worked fine. I'm sending the diff attached.

Thank you for this great script anyway !
[format-udf.sh.diff.zip](https://github.com/JElchison/format-udf/files/1643879/format-udf.sh.diff.zip)

**Comment by JElchison** [comment]
Thanks for the report!

Looks like this was introduced recently in https://github.com/pali/udftools/commit/3aef27189e3229c5ef3af3d199c2c0bee9c2c209

Are you willing to submit your fix as a pull request?  If not, no worries, I'll manually replicate your diff.

**Comment by lafleurdeboum** [comment]
Yes, I'll be glad to submit it as a pull request, let me try to do it,
that'll be my first time ! :-)

**Comment by JElchison** [comment]
Great!  If it's too much trouble, I'm happy to take care of it.  But if you submit a PR, your name will live on in the format-udf history for all time.  :)

If you'd like some tips, you can check out https://help.github.com/articles/creating-a-pull-request/

Good luck, and let me know if you have questions.

**Comment by lafleurdeboum** [comment]
OK, I think I did it - forked format-udf, and did a pull request
against the format-udf script, which I let go to upstream master
branch. I noticed a bit late that you had a "develop" branch, that I
could have pulled my request in. Hope it doesn't bother the process.
Anyway the bug fix is pretty trivial ; I also tested it on a _real_
hard drive before submitting it.
Comments appreciated !

Le jeudi 18 janvier 2018 à 10:12 -0800, JElchison a écrit :
> Great!  If it's too much trouble, I'm happy to take care of it.  But
> if you submit a PR, your name will live on in the format-udf history
> for all time.  :)
> 
> If you'd like some tips, you can check out https://help.github.com/ar
> ticles/creating-a-pull-request/
> 
> Good luck, and let me know if you have questions.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/JElchison
> /format-udf","title":"JElchison/format-udf","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/JElchison/format-
> udf"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JElchison
> in #40: Great!  If it's too much trouble, I'm happy to take care of it.  But if you submit a PR, your name will live on in the format-udf history for all time.  :)\r\n\r\nIf you'd like some tips, you can check out https://help.github.com/articles/creating-a-pull-request/\r\n\r\nGood
 luck, and let me know if you have
> questions."}],"action":{"name":"View Issue","url":"https://github.com
> /JElchison/format-udf/issues/40#issuecomment-358733449"}}}

**Comment by JElchison** [comment]
Everything looks great.  Thanks!

Your name has been automatically added to our list of contributors:
https://github.com/JElchison/format-udf/graphs/contributors
