### ISSUE TITLE
UDF File And Volume Capacity

### ISSUE THREAD

**Issue by amicalmant** [JElchison/format-udf#43]
Hi Jonathan,

FYI, I have posted a new comment on the old [WordPress blog post](https://j0nam1el.wordpress.com/2015/02/20/sharing-a-hardflash-drive-across-windows-os-x-and-linux-with-udf/) that brought me in this repository. I think it needs a little edit for posterity but maybe it's me who's missing the mark. :-)

**Comment by JElchison** [comment]
Hi @amicalmant, thanks for your question.  The blog is actually correct.

The UDF spec makes the following provisions:
- Number of blocks is limited to a 32-bit field.  This is what gives you your max volume size of 2 TiB with 512 B block size, or 16 TiB with 4 KiB block size.  See the [discussion on the format-udf README](https://github.com/JElchison/format-udf/blob/master/README.md#maximum-udf-file-system-capacity).
- Number of bytes in a single file is limited to a 64-bit field.  This is what gives you your max file size of 16 EiB.

I am unsure why the spec designers saw fit to allow files larger than the volume size.

You can verify these details yourself by reading [the actual UDF spec](http://www.osta.org/specs/).  Or, [this nice summary page](https://sites.google.com/site/udfintro/).
