### ISSUE TITLE
unknown filesystem type udf

### ISSUE THREAD

**Issue by arifainchtein** [JElchison/format-udf#45]
Hello,
I am having a problem after formatting with your script.  I am running the following commands:

`
        
        sudo mkdir /media/usb
        sudo apt-get install -y udftools coreutils vim-common
        cd /home/pi/Teleonome/build/format-udf/
        sudo chmod +x format-udf.sh
        ./format-udf.sh -f sda "MyDrive"
        echo "Mouting USB Key to /media/usb
      
`
I then take the usb out and plug it back in.  Then I execute:

`  sudo mount -t udf  /dev/sda /media/usb`

that produces the following error:

`mount: unknown filesystem type  'udf' `

Do you have any suggestions?

Thanks

**Comment by JElchison** [comment]
Hi there,

More debugging information would be helpful.  

- is the issue reproducible?
  - what are the exact environment/steps that i can use to reproduce it?
- does the issue still occur if you use a different drive?
- does the issue still occur if you use a different machine?
- what version of udftools are you using?
- what version of format-udf are you using?

Please copy and paste full output from each of the following:

- `uname -a`
- `lsb_release -a`
- `mount`
- the actual format-udf command you used and its full output
- `sudo mount -v -t udf /dev/sda /media/usb`
- any relevant output from syslog
- `sudo fdisk -l`
  - is your drive in the list?
- `sudo blkid -c /dev/null /dev/sdX`, where X is the letter associated with your drive

Thanks!
