### ISSUE TITLE
SanDisk thumb drive write speed in macOS 5x slow

### ISSUE THREAD

**Issue by hyiltiz** [JElchison/format-udf#52]
## method
I tested with `dd id=/dev/zero of=test count=200000`. The device has 512 block size. Tested in Debian testing and macOS 10.15. Tried with formatting in Debian, and formatting with macOS. Repeated the test 3-5 times in each OS. Debian was installed in Macbook Pro 9,2 and macOS was installed in Macbook 11,3. A 32 GB SanDisk cruiser SDCZ36-032G is used for all tests. None of the USB ports on the MacBook Pros look blue (not USB 3). The SanDisk USB port look red (USB 2?).

## result
In all cases, Debian wrote around 60 MB/s but macOS wrote around 8 MB/s. 

Any idea why that is the case? I'm wondering if that is due to macOS maybe implementing udf support in userspace.

**Comment by JElchison** [comment]
Hi @hyiltiz, thanks for your note!  Let me try to organize what I think you're saying.  Bear with me...

Drive under test:
- 32 GB SanDisk cruiser SDCZ36-032G
- 512-byte block size (unknown whether this is physical/logical/both)
- Red plug (which [likely indicates](https://www.quora.com/What-is-the-red-colored-USB-port-of-a-motherboard) support for USB 3.1 Gen 2)

Machine 1:
- Macbook Pro 9,2
    - [Tech specs](https://support.apple.com/kb/SP649?locale=en_US)
    - You say "not USB 3", but this model only has USB 3 ports
- Running Debian (unknown version, unknown kernel version)
- Unknown version of udftools
- Writes observed at 60 MB/s

Machine 2:
- Macbook 11,3
    - Could be [MGXC2xx/A](https://support.apple.com/kb/SP704) or [ME294xx/A](https://support.apple.com/kb/SP690), specs vary
    - You say "not USB 3", but this model only has USB 3 ports
- Running macOS 10.15
- Writes observed at 8 MB/s

Test sequence:
1. `dd id=/dev/zero of=test count=200000` to zero first portion of drive
2. Choose one of the test machines above
3. Use format-udf (unknown version, assuming 1.8.0) to format drive, using unknown parameters
4. Measure performance using [unknown method]

There are lots of unanswered questions above, but I'll ignore those for now.

The reason for the order-of-magnitude delta in your test could be attributed to any (or multiple) of the following 3 factors:
- Different physical hardware
- Different operating systems
- Different underlying UDF implementations
    - mkudffs is provided in Linux by udftools (@pali has more info)
    - newfs_udf is provided in macOS but opaque (my personal opinion is that UDF is unlikely to be implemented in userspace)

If you'd really like to get to the bottom of it, I recommend trying to eliminate 2 of the 3 variables, and repeat your testing.  Maybe try using the same physical machine for both tests?

Note:  The format-udf utility is just a wrapper for mkudffs/newfs_udf, so it's very unlikely to be a contributing factor.  As such, I'm closing this issue.

Good luck on your testing!  If you learn anything, I'd love to hear more about it in the comments below.

**Comment by hyiltiz** [comment]
Sorry my network had a hick-up and got sent twice. Thanks for the nice reformatting! I understand that `format-udf` is very unlikely to be the causing factor, but may be interested to know the issue and maybe find a workaround and format the disk that way (just like finding a work-around s.t. all three OSes can work nicely).

## Test machines environment
512 was both physical and logical block size. Debian kernel `Linux version 5.9.0-1-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.0-15) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP Debian 5.9.1-1 (2020-10-17)` `udftools 2.2-1`. `format-udf` was downloaded via `wget` from the github master 5d97a97, which is `1.8.0`.

Was *guessing* not USB3 since I assumed all USB3 was blue-coded. 

## Test method
The `test` in `dd id=/dev/zero of=test count=200000` was just a file in the root directory of the drive (re-)formatted by `format-udf`. I used the default parameters for `format-udf`, and also tried varying (logical) block size but that failed. The performance metric used is the write speed (`bytes/s`, BSD/macOS `dd` and Debian `dd` reported in different units so I converted them both to it) reported by `dd`.

Thanks for the suggestion! The difference in physical hardware and OS is slightly tricky to deal with but possible. My dual-boot setup keeps getting wrecked every time one of the OSes decide to wipe the boot loader configs of the other. Maybe a virtual OS is a good workaround, that can keep the whole environment the same. But then, that may be just replicating your travis environment... Any suggestions for using virtualization vs. native OS installation?

**Comment by JElchison** [comment]
Thanks for all of the answers and clarifications!

A few ideas:
- I can't guarantee that `dd` chooses the same default block size (`bs` param) across OSes.  Consider making that explicit, to ensure comparing apples to apples?
- Since your test file is all zeroes, you may be seeing different performance numbers due to caching.  I recommend using `/dev/urandom` to seed your `test` file
- `dd` is hardly a robust benchmarking mechanism.  You may wish to consider other file system benchmarking suites out there.  [Here's one of the first](https://docs.gitlab.com/ee/administration/operations/filesystem_benchmarking.html) I saw in my search.
- If you're benchmarking performance, physical machines will always be better than virtual ones.  Dual-booting on one physical machine successfully removes one (large) variable from the equation.

**Comment by hyiltiz** [comment]
I did try with explicitly setting `bs` for `dd` and they were both the same. I didn't use the random device since that could have vastly different across the two OSes, but I can try that out. I'll check out `fio`. Also, maybe just create a large file first then time how long it takes to `cp` it. May take a while to fix dual-booting for now, and would rather not meddle with my working machine as that could, you know, trash it for some (unpredictable) while until I fix it properly. I'll report back.
