### ISSUE TITLE
Not readable in Windows 7

### ISSUE THREAD

**Issue by BenKennish** [JElchison/format-udf#7]
Thanks for the handy script.  8-)

I'm having a few problems getting the drive recognised by Windows 7 tho.  I just attached my 64GB USB Flash drive to a VirtualBox guest running CentOS 7.  I ran:

```
$ sudo ./format-udf.sh sdb "Gordon"
[+] Testing dependencies...
[+] Looking for drive listing tool...which: no diskutil in (/sbin:/bin:/usr/sbin:/usr/bin)
 using /sbin/blockdev
[+] Looking for unmount tool...which: no diskutil in (/sbin:/bin:/usr/sbin:/usr/bin)
 using /bin/umount
[+] Looking for UDF tool...which: no newfs_udf in (/sbin:/bin:/usr/sbin:/usr/bin)
 using /bin/mkudffs
[+] Validating arguments...
[+] Gathering drive information...
Cruzer Edge     
RO    RA   SSZ   BSZ   StartSec            Size   Device
rw   256   512   512          0     64016220160   /dev/sdb
The above-listed drive (and partitions, if any) will be completely erased.
Type 'yes' if this is what you intend:  yes
[+] Detecting native sector size...
[+] Validating detected sector size...
[+] Unmounting drive...
[+] Zeroing out any existing partition table on drive...
4096+0 records in
4096+0 records out
2097152 bytes (2.1 MB) copied, 5.91336 s, 355 kB/s
[+] Formatting /dev/sdb ...
start=0, blocks=64, type=RESERVED 
start=64, blocks=12, type=VRS 
start=76, blocks=180, type=USPACE 
start=256, blocks=1, type=ANCHOR 
start=257, blocks=16, type=PVDS 
start=273, blocks=1, type=LVID 
start=274, blocks=125031149, type=PSPACE 
start=125031423, blocks=1, type=ANCHOR 
start=125031424, blocks=239, type=USPACE 
start=125031663, blocks=16, type=RVDS 
start=125031679, blocks=1, type=ANCHOR 
[*] Successfully formatted /dev/sdb: LABEL="Gordon" TYPE="udf" 
Please disconnect/reconnect your drive now.
[ben@bentos7 format-udf]$ 
```

The CentOS 7 guest itself seems happy enough with things - if I disconnect and reconnect the drive, it recognises it and I can view, create folders and files, etc.

However, I cannot get Windows to use the drive.  I safely remove the drive from CentOS and disconnect it from the VirtualBox guest.  In Windows I then go to "Computer Management" and "Disk Management" and a pop-up window tells  me "You must initialize a disk before Logical Disk Manager" can access it.  I assume this is because of the zeroing of the first part of the disk?  How do I go about attaching a drive letter to the newly created disk?

Cheers, Ben

**Comment by JElchison** [comment]
Hi @BenKennish and @pali,

I've recently encountered some drives that regularly exhibit the problem both of you have experienced.  I'm interested in characterizing the problem.  Would you be willing to help by adding info about your problem drive(s) to the table on [this wiki page](https://github.com/JElchison/format-udf/wiki/Windows-has-trouble-recognizing-UDF-block-devices)?

With my preliminary data, it appears that Windows somehow differentiates block devices according to whether they're a Flash drive or HDD.

Thanks!

**Comment by JElchison** [comment]
Oh, also:  If you can do without some of the POSIX-compatible features, [exFAT](https://en.wikipedia.org/wiki/ExFAT) isn't a bad alternative to UDF.  It's natively supported in both Windows and OS X.  In Linux, you can enable support with third-party utilities.  In Ubuntu, this simply means ```sudo apt-get install exfat-utils exfat-fuse```

**Comment by pali** [comment]
No, exFAT is even worse as you can imagine! Also it is full of MS patents and without specification. There is no usable Linux support (that fuse stuff is slow and unstable, nothing for real data storage). And exFAT does not solve any FAT32 filesystems problems (except filesize limit per file). So I do not see any reason why to use exFAT.

**Comment by JElchison** [comment]
@pali:  I don't disagree.  But, for people who care more about compatibility than performance, do you have a better cross-platform alternative to UDF?

FWIW, exFAT also improves on FAT32 with maximum volume size and allowable characters in directory entries.  For a quick summary, see [this page](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits).

**Comment by pali** [comment]
No, there is no other alternative. Windows supports only FAT12, FAT16, FAT32, NTFS, exFAT and UDF. (Plus ISO9660 which it is read-only)

I do not know who can prefer compatiblity instead *stable* quality... (maybe just some testers who plays with filesystems). Filesystem is for storing data files and it must be stable... I do not know any stable implementation of NTFS or exFAT except one from Microsoft. I saw NTFS filesystem which was damaged by fuse ntfs-3g... For me ntfs and exfat fuse implementation are (very) useful only for data recovery.

So there is only FAT32 and UDF, just choose between those two. I think that Linux and Apple systems have stable implementation of FAT and UDF (or at least more stable as for exFAT or NTFS). But there is no Linux fsck tool for UDF (you can still use one on MS or Apple system).

**Comment by JElchison** [comment]
Hi @BenKennish and @pali,

I've recently made some updates to format-udf that you may be interested in.  Version 1.1.0 of the tool includes a new feature that writes a fake MBR for added UDF compatibility on Windows.

If you're interested in giving it a try, I'm interested in learning whether the new version addresses your issues.  Please report back in this thread.  thanks!
