### ISSUE TITLE
Write support in Windows XP/2003 not availiable at all

### ISSUE THREAD

**Issue by mittorn** [JElchison/format-udf#8]
All third-party utilites just only works with cd/dvd, not usb flash.
If there is any utility that can work with usb flash, give me a link :)

**Comment by Zero3K20** [comment]
There's an open source UDFS driver that I am having a guy work on. You can try the code in the write or udf-dev branches of https://github.com/assorted/reactos.

**Comment by mittorn** [comment]
It was 11 years ago and I'm not use Windows (especially 5.x) anymore, but 
that's sounds interesting!
